"""staff tables

Revision ID: 3a6665fc8914
Revises: f860cbbb92f8
Create Date: 2024-07-13 10:58:15.267297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a6665fc8914'
down_revision = 'f860cbbb92f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hedgehogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hedgehog_under_care', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['hedgehog_under_care'], ['hedgehogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permanent_staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('years_of_experience', sa.Integer(), nullable=False),
    sa.Column('staffkey', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['staffkey'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('volunteer_staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hours', sa.Integer(), nullable=False),
    sa.Column('staffkey', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['staffkey'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volunteer_staff')
    op.drop_table('permanent_staff')
    op.drop_table('staff')
    op.drop_table('hedgehogs')
    # ### end Alembic commands ###
