"""rename type to staff_type

Revision ID: d2c633038a1b
Revises: 3a6665fc8914
Create Date: 2024-07-13 12:34:44.141031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2c633038a1b'
down_revision = '3a6665fc8914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff_type', sa.String(length=50), nullable=False))
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('staff_type')

    # ### end Alembic commands ###
