"""adjust id columns in staff models

Revision ID: e4ca9c9bc415
Revises: d2c633038a1b
Create Date: 2024-07-13 23:24:04.210764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4ca9c9bc415'
down_revision = 'd2c633038a1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permanent_staff', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_permanent_staff_id', 'staff', ['id'], ['id'])

    with op.batch_alter_table('volunteer_staff', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_volunteer_staff_id', 'staff', ['id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_staff', schema=None) as batch_op:
        batch_op.drop_constraint('fk_volunteer_staff_id', type_='foreignkey')

    with op.batch_alter_table('permanent_staff', schema=None) as batch_op:
        batch_op.drop_constraint('fk_permanent_staff_id', type_='foreignkey')
    # ### end Alembic commands ###
